### ISSUE TITLE
TypeError when accessing page.text

### ISSUE THREAD

**Issue by adamball** [yob/pdf-reader#111]
Hello,

Using Windows 7 and Ruby 1.9.3

I'm currently attempting to parse a large collection of PDF bank statements.  I am accessing the 'text' attribute of each page in each PDF::Reader object, and on a certain collection of statements, I get the following:

```
#<TypeError: can't convert nil into String>
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/buffer.rb:235:in `prepare_inline_token'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/buffer.rb:175:in `block in prepare_tokens'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/buffer.rb:170:in `times'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/buffer.rb:170:in `prepare_tokens'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/buffer.rb:116:in `token'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/parser.rb:73:in `parse_token'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/form_xobject.rb:84:in `tokens'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/form_xobject.rb:94:in `content_stream'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/form_xobject.rb:47:in `walk'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page_text_receiver.rb:88:in `block in invoke_xobject'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page_state.rb:202:in `invoke_xobject'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page_text_receiver.rb:85:in `invoke_xobject'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page.rb:154:in `block in callback'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page.rb:153:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page.rb:153:in `callback'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page.rb:140:in `content_stream'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page.rb:105:in `walk'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page.rb:75:in `text'
C:/Users/tokyo/Google Drive/projects/ruby/read_bank_pdfs/read_pdf.rb:25:in `block (2 levels) in <top (required)>'
C:/Users/tokyo/Google Drive/projects/ruby/read_bank_pdfs/read_pdf.rb:23:in `each'
C:/Users/tokyo/Google Drive/projects/ruby/read_bank_pdfs/read_pdf.rb:23:in `block in <top (required)>'
C:/Users/tokyo/Google Drive/projects/ruby/read_bank_pdfs/read_pdf.rb:21:in `each'
C:/Users/tokyo/Google Drive/projects/ruby/read_bank_pdfs/read_pdf.rb:21:in `<top (required)>'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/ruby-debug-ide-0.4.17.beta17/lib/ruby-debug-ide.rb:86:in `debug_load'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/ruby-debug-ide-0.4.17.beta17/lib/ruby-debug-ide.rb:86:in `debug_program'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/ruby-debug-ide-0.4.17.beta17/bin/rdebug-ide:109:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'
```

I've read pretty extensively through the source, and I can see exactly when it's going to parse the given token, but I can't seem to root out the source of the issue.  

Currently I've been trying to throw some begin blocks around the parsing sections, however this doesn't seem to catch the issue.  It should be noted each time this occurs, there are other pages in the PDF::Reader object that go through successfully.

Not really sure where to go with this one.  Not sure if they're just malformed PDF files or if there's something else afoot.  Unfortunately I cannot share the PDFs, as they're bank statements and contain personal information.  Any guidance would be appreciated.

Here is the script I am using, i'm simply rooting out the bad ones by trivially accessing the text block:

``` ruby
$:.unshift File.dirname(__FILE__)

require 'pdf-reader'
require 'awesome_print'
require 'lib/statement'

issue_array = []
pdf_files = []
pdf_path = File.path(File.dirname(__FILE__) + '/bankingStatements/')
statement_array = []

# find all pdf files for processing
Dir.chdir(pdf_path)
Dir.glob('*.pdf').each { |file| pdf_files << pdf_path + file }

pdf_files.each do |pdf|
  reader_object = PDF::Reader.new(pdf)
  statement_array << Statement.new({:reader_object => reader_object, :file_name => pdf})
end

statement_array.each do |statement|
  i = 1

  statement.reader_object.pages.each do |page|
    begin
      puts "#{page.text.length}"
    rescue Exception => e
      $stderr.puts(e.to_s)
      issue_array << { :file => statement.file_name, :page => i }
    end
    i += 1
  end
end

#ap issue_array

File.delete('C:\Users\tokyo\Desktop\out.txt')
f = File.new('C:\Users\tokyo\Desktop\out.txt', 'a')

issue_array.each do |a|
  f << "#{a}\n"
end
```

Thank you,
Adam

**Comment by yob** [comment]
Thanks for taking the time to report this, and apologies for taking so long to review it.

This looks like a bug in the parsing logic for inline images. That code is a bit rough, so if there's an issue there then I'm not too surprised.

Without a sample file it's hard to investigate further though. I'm going to close this issue for now, but please re-open it if further information becomes available.
