### ISSUE TITLE
 PDFReader - MalformedPDFError - Error occured while inflating a compressed stream

### ISSUE THREAD

**Issue by ramyakp** [yob/pdf-reader#131]
Hello,
Thanks for the wonderful gem.

I am encountering an issue on few PDFs - I get PDF::Reader::MalformedPDFError: Error occured while inflating a compressed stream  when i try to read the Page text 'reader.pages[1].text'.
Here is the complete error details. Can someone please help here?

Details:
# <PDF::Reader::MalformedPDFError: Error occured while inflating a compressed stream (Zlib::DataError: invalid code lengths set)> Additional Details: C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/filter/flate.rb:34:in `rescue in filter' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/filter/flate.rb:17:in`filter' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/stream.rb:63:in `block in unfiltered_data' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/stream.rb:62:in`each' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/stream.rb:62:in `each_with_index' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/stream.rb:62:in`unfiltered_data' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/font.rb:136:in `extract_base_info' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/font.rb:47:in`initialize' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page_state.rb:384:in `new' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page_state.rb:384:in`block in build_fonts' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page_state.rb:383:in `each' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page_state.rb:383:in`map' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page_state.rb:383:in `build_fonts' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page_state.rb:28:in`initialize' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page_text_receiver.rb:42:in `new' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page_text_receiver.rb:42:in`page=' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page.rb:154:in `block in callback' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page.rb:153:in`each' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page.rb:153:in `callback' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page.rb:104:in`walk' C:/Ruby193/lib/ruby/gems/1.9.1/gems/pdf-reader-1.3.3/lib/pdf/reader/page.rb:75:in `text' C:/Tellus/Utils/UtilsBB.rb:32:in`VerifyPDFDownloaded'

Regards,
Ramya

**Comment by wyefei** [comment]
Hey @yob I have a sample PDF having this problem. Can you take a look?

**Comment by jamescgibson** [comment]
I too have run into this problem. Have yet to find a solution.

**Comment by yob** [comment]
Closing as stale. I'll be happy to take a fresh look if someone can provide a sample PDF
