### ISSUE TITLE
`page_references': undefined method `flatten' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by bcoles** [yob/pdf-reader#194]
**Environment**

* Ruby version 2.3.1
* pdf-reader version 1.4.1
* Ubuntu Linux

**Steps to reproduce:**

```bash
$ wget http://www.asx.com.au/asxpdf/20161214/pdf/43dqk3sg14cqqf.pdf
```

```ruby
#!/usr/bin/env ruby
require 'pdf-reader'

begin
  reader = PDF::Reader.new('43dqk3sg14cqqf.pdf')
rescue => e
  puts "Could not parse PDF: #{e}"
end

puts 'Read PDF successfully'
puts "PDF version: #{reader.pdf_version}"
puts "Pages: #{reader.page_count}"

reader.pages.each do |page|
  page.text
end
```

```
$ ./bug.rb 
Read PDF successfully
PDF version: 1.5
Pages: 2
/usr/local/rvm/gems/ruby-2.3.1/gems/pdf-reader-1.4.1/lib/pdf/reader/object_hash.rb:256:in `page_references': undefined method `flatten' for nil:NilClass (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.3.1/gems/pdf-reader-1.4.1/lib/pdf/reader/page.rb:35:in `initialize'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/pdf-reader-1.4.1/lib/pdf/reader.rb:238:in `new'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/pdf-reader-1.4.1/lib/pdf/reader.rb:238:in `block in pages'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/pdf-reader-1.4.1/lib/pdf/reader.rb:237:in `each'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/pdf-reader-1.4.1/lib/pdf/reader.rb:237:in `map'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/pdf-reader-1.4.1/lib/pdf/reader.rb:237:in `pages'
	from ./bug.rb:14:in `<main>'
```

**Comment by yob** [comment]
Thanks for reporting this. By co-incidence, it looks like this is the same issue that was reported in #174 and a fix was recently applied to master

**Comment by bcoles** [comment]
Thanks @yob - I searched issues but missed the PR
