### ISSUE TITLE
TypeError while reading a pdf

### ISSUE THREAD

**Issue by MathieuDerelle** [yob/pdf-reader#206]
I'm getting an error which is neither MalformedPDFError or UnsupportedFeatureError when trying to read this pdf
[20170304-1134-6333-314589-1.pdf](https://github.com/yob/pdf-reader/files/833798/20170304-1134-6333-314589-1.pdf)

trace : 
```
[10] pry(main)> reader = PDF::Reader.new(path);
[11] pry(main)> reader.pages[0].text
TypeError: no implicit conversion of nil into String
/Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/buffer.rb:237:in `prepare_inline_token'
/Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/buffer.rb:177:in `block in prepare_tokens'
/Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/buffer.rb:172:in `times'
/Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/buffer.rb:172:in `prepare_tokens'
/Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/buffer.rb:118:in `token'
/Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/parser.rb:134:in `pdf_name'
/Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/parser.rb:37:in `block in <class:Parser>'
/Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/parser.rb:76:in `call'
/Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/parser.rb:76:in `parse_token'
/Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:144:in `content_stream'
/Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:111:in `walk'
/Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:81:in `text'
(pry):11:in `__pry__'
```

**Comment by MathieuDerelle** [comment]
wow, I forgot I had already posted this one before submitting https://github.com/yob/pdf-reader/issues/213
