### ISSUE TITLE
Malformed PDF causes hang with 100% CPU usage

### ISSUE THREAD

**Issue by bcoles** [yob/pdf-reader#217]
pdf-reader hangs with 100% CPU usage when parsing the attached corrupt/malformed PDF.

[hang.pdf](https://github.com/yob/pdf-reader/files/1133060/hang.pdf)

```
$ ./hang.rb hang.pdf 
Processing 'hang.pdf'
^C/usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/buffer.rb:178:in `block in prepare_tokens': Interrupt
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/buffer.rb:172:in `times'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/buffer.rb:172:in `prepare_tokens'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/buffer.rb:118:in `token'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/xref.rb:131:in `block in load_xref_table'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/xref.rb:128:in `times'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/xref.rb:128:in `load_xref_table'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/xref.rb:105:in `load_offsets'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/xref.rb:60:in `initialize'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/object_hash.rb:44:in `new'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/object_hash.rb:44:in `initialize'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader.rb:116:in `new'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader.rb:116:in `initialize'
	from ./hang.rb:19:in `new'
	from ./hang.rb:19:in `<main>'
```

```
$ cat hang.rb 
#!/usr/bin/env ruby
require 'pdf-reader'

def usage
  puts "./hang.rb <FILE>"
  exit 1
end

doc = ARGV[0]
usage if doc.nil?

unless File.exist? doc
  puts "Error: could not find #{doc}"
  exit 1
end

puts "Processing '#{doc}'"
begin
  reader = PDF::Reader.new doc
rescue PDF::Reader::MalformedPDFError
  puts "Error: could not parse PDF '#{doc}': PDF is malformed"
  exit 1
rescue PDF::Reader::UnsupportedFeatureError
  puts "Error: could not parse PDF '#{doc}': PDF::Reader::UnsupportedFeatureError"
  exit 1
end
puts 'Processing complete'
```

**Comment by yob** [comment]
I've looked into this and confirmed the issue.

The xref table starts with:

```
1152 xref
1153 < 85
1154 0000000000 65535 f
```

That `<` should be a `0`. `PDF::Reader::Buffer` notices the `<` and thinks it's parsing a hex string, causing it to read ahead looking for a `>` rather than following standard tokenising rules.

I'll put some thought into a suitable approach to avoiding a hard loop.
