### ISSUE TITLE
Malformed PDF raises `stack level too deep (SystemStackError)`

### ISSUE THREAD

**Issue by bcoles** [yob/pdf-reader#231]
pdf-reader crashes with the attached malformed PDF file.

[stack_level.pdf](https://github.com/yob/pdf-reader/files/1133179/stack_level.pdf)

### Crash

```
[*] Processing 'stack_level.pdf'
[+] Processing complete
[*] Parsing 'stack_level.pdf'
[*] Version: 1.3
[*] Info: {:Title=>#<PDF::Reader::Reference:0x00000000cce0c0 @id=98, @gen=0>, :Author=>#<PDF::Reader::Reference:0x00000000ccc978 @id=100, @gen=0>, :Subject=>#<PDF::Reader::Reference:0x00000000ccc518 @id=101, @gen=0>, :Producer=>#<PDF::Reader::Reference:0x00000000cbb470 @id=99, @gen=0>, :Creator=>#<PDF::Reader::Reference:0x00000000cbafc0 @id=102, @gen=0>, :CreationDate=>#<PDF::Reader::Reference:0x00000000cb7f00 @id=103, @gen=0>, :ModDate=>#<PDF::Reader::Reference:0x00000000cb7aa0 @id=103, @gen=0>, :Keywords=>#<PDF::Reader::Reference:0x00000000cb63d0 @id=104, @gen=0>, :"AAPL:Keywords"=>#<PDF::Reader::Reference:0x00000000cb5fc0 @id=105, @gen=0>}
[*] Metadata: 
[*] Objects: <PDF::Reader::ObjectHash size: 99>
[*] Pages: 6
[*] Dumping PDF contents...
/usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/object_cache.rb:71:in `include?': stack level too deep (SystemStackError)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/object_cache.rb:71:in `include?'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/object_cache.rb:96:in `update_stats'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/object_cache.rb:28:in `[]'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/object_hash.rb:81:in `[]'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/object_hash.rb:98:in `object'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/object_hash.rb:342:in `get_page_objects'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/object_hash.rb:347:in `block in get_page_objects'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/object_hash.rb:347:in `map'
	 ... 11218 levels...
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader.rb:176:in `pages'
	from ./read-pdf.rb:78:in `parse'
	from ./read-pdf.rb:55:in `read'
	from ./read-pdf.rb:96:in `<main>'
```

### Reproduce

```
#!/usr/bin/env ruby
require 'pdf-reader'
require 'colorize'

$QUIET = false

#
# Print status message
#
# @param [String] msg message to print
#
def print_status(msg = '')
  puts '[*] '.blue + msg unless $QUIET
end

#
# Print progress messages
#
# @param [String] msg message to print
#
def print_good(msg = '')
  puts '[+] '.green + msg unless $QUIET
end

#
# Print error message
#
# @param [String] msg message to print
#
def print_error(msg = '')
  puts '[-] '.red + msg unless $QUIET
end

#
# Read a PDF file
#
# @param [File] file PDF file
#
def read doc
  print_status "Processing '#{doc}'"
  begin
    @fname = doc
    reader = PDF::Reader.new(@fname)
  rescue PDF::Reader::MalformedPDFError
    print_error "Could not parse PDF '#{doc}': PDF is malformed"
    exit 1
  rescue PDF::Reader::UnsupportedFeatureError 
    print_error "Could not parse PDF '#{doc}': PDF::Reader::UnsupportedFeatureError"
    exit 1
  end
  print_good 'Processing complete'

  print_status "Parsing '#{@fname}'"
  begin
    parse reader
  rescue PDF::Reader::UnsupportedFeatureError
    print_error "Could not parse PDF '#{doc}': PDF::Reader::UnsupportedFeatureError"
    exit 1
  rescue PDF::Reader::MalformedPDFError => e
    print_error "Could not parse PDF '#{doc}': PDF is malformed"
    exit 1
  end
  print_good 'Parsing complete'
end

#
# parse pdf
#
def parse(reader)
  print_status "Version: #{reader.pdf_version}"
  print_status "Info: #{reader.info}"
  print_status "Metadata: #{reader.metadata}"
  print_status "Objects: #{reader.objects}"
  print_status "Pages: #{reader.page_count}"

  print_status 'Dumping PDF contents...'
  contents = ''
  reader.pages.each do |page|
    contents << page.text.to_s
    contents << page.fonts.to_s
    contents << page.text.to_s
    contents << page.raw_content.to_s
  end
  #puts contents unless $QUIET
end

def usage
  print_status "./read-pdf.rb <FILE>"
  exit 1
end

doc = ARGV[0]
usage if doc.nil?

if File.exist? doc
  read doc
  exit 0
else
  print_error "Could not find #{doc}"
  exit 1
end
```

**Comment by bcoles** [comment]
This issue is problematic as `SystemStackError` will not be handled by a `rescue` clause unless the author is in the bad habit of using `rescue Exception`.
