### ISSUE TITLE
Malformed PDF raises `undefined method `/' for nil:NilClass (NoMethodError)`

### ISSUE THREAD

**Issue by bcoles** [yob/pdf-reader#240]
pdf-reader crashes with the attached malformed PDF file.

[20170708145744296746664_test_0784.pdf](https://github.com/yob/pdf-reader/files/1133229/20170708145744296746664_test_0784.pdf)

### Crash

```
[*] Processing 'crashes/20170708145744296746664_test_0784.pdf'
[+] Processing complete
[*] Parsing 'crashes/20170708145744296746664_test_0784.pdf'
[*] Version: 1.3
[*] Info: {:Title=>#<PDF::Reader::Reference:0x000000027adaf8 @id=98, @gen=0>, :Author=>#<PDF::Reader::Reference:0x000000027a32b0 @id=100, @gen=0>, :Subject=>#<PDF::Reader::Reference:0x000000027a2c70 @id=101, @gen=0>, :Producer=>#<PDF::Reader::Reference:0x000000027a0330 @id=99, @gen=0>, :Creator=>#<PDF::Reader::Reference:0x0000000279fd40 @id=102, @gen=0>, :CreationDate=>#<PDF::Reader::Reference:0x0000000279d8d8 @id=103, @gen=0>, :ModDate=>#<PDF::Reader::Reference:0x0000000279d338 @id=103, @gen=0>, :Keywords=>#<PDF::Reader::Reference:0x0000000278d7a8 @id=104, @gen=0>, :"AAPL:Keywords"=>#<PDF::Reader::Reference:0x0000000278d398 @id=105, @gen=0>}
[*] Metadata: 
[*] Objects: <PDF::Reader::ObjectHash size: 105>
[*] Pages: 6
[*] Dumping PDF contents...
/usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page_text_receiver.rb:107:in `block in internal_show_text': undefined method `/' for nil:NilClass (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page_text_receiver.rb:100:in `each'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page_text_receiver.rb:100:in `each_with_index'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page_text_receiver.rb:100:in `internal_show_text'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page_text_receiver.rb:57:in `show_text'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:160:in `block in callback'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:159:in `each'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:159:in `callback'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:146:in `content_stream'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:111:in `walk'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:81:in `text'
	from ./read-pdf.rb:79:in `block in parse'
	from ./read-pdf.rb:78:in `each'
	from ./read-pdf.rb:78:in `parse'
	from ./read-pdf.rb:55:in `read'
	from ./read-pdf.rb:96:in `<main>'
```

### Reproduce

```
#!/usr/bin/env ruby
require 'pdf-reader'
require 'colorize'

$QUIET = false

#
# Print status message
#
# @param [String] msg message to print
#
def print_status(msg = '')
  puts '[*] '.blue + msg unless $QUIET
end

#
# Print progress messages
#
# @param [String] msg message to print
#
def print_good(msg = '')
  puts '[+] '.green + msg unless $QUIET
end

#
# Print error message
#
# @param [String] msg message to print
#
def print_error(msg = '')
  puts '[-] '.red + msg unless $QUIET
end

#
# Read a PDF file
#
# @param [File] file PDF file
#
def read doc
  print_status "Processing '#{doc}'"
  begin
    @fname = doc
    reader = PDF::Reader.new(@fname)
  rescue PDF::Reader::MalformedPDFError
    print_error "Could not parse PDF '#{doc}': PDF is malformed"
    exit 1
  rescue PDF::Reader::UnsupportedFeatureError 
    print_error "Could not parse PDF '#{doc}': PDF::Reader::UnsupportedFeatureError"
    exit 1
  end
  print_good 'Processing complete'

  print_status "Parsing '#{@fname}'"
  begin
    parse reader
  rescue PDF::Reader::UnsupportedFeatureError
    print_error "Could not parse PDF '#{doc}': PDF::Reader::UnsupportedFeatureError"
    exit 1
  rescue PDF::Reader::MalformedPDFError => e
    print_error "Could not parse PDF '#{doc}': PDF is malformed"
    exit 1
  end
  print_good 'Parsing complete'
end

#
# parse pdf
#
def parse(reader)
  print_status "Version: #{reader.pdf_version}"
  print_status "Info: #{reader.info}"
  print_status "Metadata: #{reader.metadata}"
  print_status "Objects: #{reader.objects}"
  print_status "Pages: #{reader.page_count}"

  print_status 'Dumping PDF contents...'
  contents = ''
  reader.pages.each do |page|
    contents << page.text.to_s
    contents << page.fonts.to_s
    contents << page.text.to_s
    contents << page.raw_content.to_s
  end
  #puts contents unless $QUIET
end

def usage
  print_status "./read-pdf.rb <FILE>"
  exit 1
end

doc = ARGV[0]
usage if doc.nil?

if File.exist? doc
  read doc
  exit 0
else
  print_error "Could not find #{doc}"
  exit 1
end
```

**Comment by m-an** [comment]
Hello @bcoles , have you found any workaround? that is definetely related to fonts in pdf.
For me it works if I convert my bad pdf to doc and then back to pdf with some online services which provide this functionality. If you open pdfs after this, you will definetely see the fonts will be different.
But I just was wondering, maybe you found some better solution?

**Comment by bcoles** [comment]
@m-an sorry, no I don't have a solution. I identified this bug while fuzzing the code.
