### ISSUE TITLE
Malformed PDF raises `Infinity (FloatDomainError)`

### ISSUE THREAD

**Issue by bcoles** [yob/pdf-reader#243]
pdf-reader crashes with the attached malformed PDF file.

[20170708165521936469335_test_0010.pdf](https://github.com/yob/pdf-reader/files/1133312/20170708165521936469335_test_0010.pdf)

### Crash

```
[*] Processing 'crashes/20170708165521936469335_test_0010.pdf'
[+] Processing complete
[*] Parsing 'crashes/20170708165521936469335_test_0010.pdf'
[*] Version: 1.3
[*] Info: {:CreationDate=>"D:200805060928", :Creator=>"brazil.rb", :Producer=>"PDF::Writer for Ruby"}
[*] Metadata: 
[*] Objects: <PDF::Reader::ObjectHash size: 9>
[*] Pages: 1
[*] Dumping PDF contents...
/usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page_layout.rb:64:in `floor': Infinity (FloatDomainError)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page_layout.rb:64:in `col_count'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page_layout.rb:29:in `block in to_s'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page_layout.rb:29:in `times'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page_layout.rb:29:in `each'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page_layout.rb:29:in `map'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page_layout.rb:29:in `to_s'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page_text_receiver.rb:49:in `content'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:82:in `text'
	from ./read-pdf.rb:79:in `block in parse'
	from ./read-pdf.rb:78:in `each'
	from ./read-pdf.rb:78:in `parse'
	from ./read-pdf.rb:55:in `read'
	from ./read-pdf.rb:96:in `<main>'
```

### Reproduce

```
#!/usr/bin/env ruby
require 'pdf-reader'
require 'colorize'

$QUIET = false

#
# Print status message
#
# @param [String] msg message to print
#
def print_status(msg = '')
  puts '[*] '.blue + msg unless $QUIET
end

#
# Print progress messages
#
# @param [String] msg message to print
#
def print_good(msg = '')
  puts '[+] '.green + msg unless $QUIET
end

#
# Print error message
#
# @param [String] msg message to print
#
def print_error(msg = '')
  puts '[-] '.red + msg unless $QUIET
end

#
# Read a PDF file
#
# @param [File] file PDF file
#
def read doc
  print_status "Processing '#{doc}'"
  begin
    @fname = doc
    reader = PDF::Reader.new(@fname)
  rescue PDF::Reader::MalformedPDFError
    print_error "Could not parse PDF '#{doc}': PDF is malformed"
    exit 1
  rescue PDF::Reader::UnsupportedFeatureError 
    print_error "Could not parse PDF '#{doc}': PDF::Reader::UnsupportedFeatureError"
    exit 1
  end
  print_good 'Processing complete'

  print_status "Parsing '#{@fname}'"
  begin
    parse reader
  rescue PDF::Reader::UnsupportedFeatureError
    print_error "Could not parse PDF '#{doc}': PDF::Reader::UnsupportedFeatureError"
    exit 1
  rescue PDF::Reader::MalformedPDFError => e
    print_error "Could not parse PDF '#{doc}': PDF is malformed"
    exit 1
  end
  print_good 'Parsing complete'
end

#
# parse pdf
#
def parse(reader)
  print_status "Version: #{reader.pdf_version}"
  print_status "Info: #{reader.info}"
  print_status "Metadata: #{reader.metadata}"
  print_status "Objects: #{reader.objects}"
  print_status "Pages: #{reader.page_count}"

  print_status 'Dumping PDF contents...'
  contents = ''
  reader.pages.each do |page|
    contents << page.text.to_s
    contents << page.fonts.to_s
    contents << page.text.to_s
    contents << page.raw_content.to_s
  end
  #puts contents unless $QUIET
end

def usage
  print_status "./read-pdf.rb <FILE>"
  exit 1
end

doc = ARGV[0]
usage if doc.nil?

if File.exist? doc
  read doc
  exit 0
else
  print_error "Could not find #{doc}"
  exit 1
end
```

**Comment by Mifrill** [comment]
I also got this error on the first page
I just skipped this page, the rest of the document is read correctly

```
  def text(number = 0)
    text = ""

    PDF::Reader.new(file).pages[number..-1].each do |page|
      text += "\n" + page.text
    end

    text
  end
```

**Comment by oamado** [comment]
any new about this issue? I'm getting the same error and is only one page PDF, so I can't skip it

**Comment by oamado** [comment]
Is possible to fix the file with ghostscript
https://superuser.com/questions/278562/how-can-i-fix-repair-a-corrupted-pdf-file

**Comment by zealot128** [comment]
I've created an issue with example code in #339
