### ISSUE TITLE
undefined method `unfiltered_data'

### ISSUE THREAD

**Issue by tit** [yob/pdf-reader#252]
```
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

$ gem list pdf-reader
pdf-reader (2.0.0)

$ pdf_text tracking.pdf 
/Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/lib/pdf/reader/font.rb:127:in `extract_base_info': undefined method `unfiltered_data' for :"Identity-H":Symbol (NoMethodError)
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/lib/pdf/reader/font.rb:43:in `initialize'
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/lib/pdf/reader/page_state.rb:383:in `new'
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/lib/pdf/reader/page_state.rb:383:in `block in build_fonts'
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/lib/pdf/reader/page_state.rb:382:in `each'
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/lib/pdf/reader/page_state.rb:382:in `map'
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/lib/pdf/reader/page_state.rb:382:in `build_fonts'
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/lib/pdf/reader/page_state.rb:28:in `initialize'
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/lib/pdf/reader/page_text_receiver.rb:42:in `new'
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/lib/pdf/reader/page_text_receiver.rb:42:in `page='
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:160:in `block in callback'
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:159:in `each'
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:159:in `callback'
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:110:in `walk'
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:81:in `text'
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/bin/pdf_text:12:in `block in <top (required)>'
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/bin/pdf_text:11:in `each'
	from /Users/tit/.rvm/gems/ruby-2.3.1/gems/pdf-reader-2.0.0/bin/pdf_text:11:in `<top (required)>'
	from /Users/tit/.rvm/gems/ruby-2.3.1/bin/pdf_text:23:in `load'
	from /Users/tit/.rvm/gems/ruby-2.3.1/bin/pdf_text:23:in `<main>'
	from /Users/tit/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tit/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

Problem pdf https://drive.google.com/file/d/0B-089WfiiEcXZGc3TTRMVnBRbVE
What am I doing wrong?

**Comment by yob** [comment]
Thanks for the bug report and sample file.

You were doing nothing wrong, this was a bug in pdf-reader.
