### ISSUE TITLE
PDF::Reader::EncryptedPDFError on a USCIS form

### ISSUE THREAD

**Issue by ndbroadbent** [yob/pdf-reader#254]
To reproduce, run this in the terminal:

```bash
wget "https://www.uscis.gov/system/files_force/files/form/i-130.pdf?download=1" -O /tmp/i-130.pdf
ruby -e "require 'pdf-reader'; PDF::Reader.new('/tmp/i-130.pdf').page_count"
```

Result:

```bash
$ ruby -e "require 'pdf-reader'; PDF::Reader.new('/tmp/i-130.pdf').page_count"
/Users/ndbroadbent/.rvm/gems/ruby-2.4.0/gems/pdf-reader-2.0.0/lib/pdf/reader/unimplemented_security_handler.rb:13:in `decrypt': Unsupported encryption style (PDF::Reader::EncryptedPDFError)
	from /Users/ndbroadbent/.rvm/gems/ruby-2.4.0/gems/pdf-reader-2.0.0/lib/pdf/reader/object_hash.rb:313:in `decrypt'
	from /Users/ndbroadbent/.rvm/gems/ruby-2.4.0/gems/pdf-reader-2.0.0/lib/pdf/reader/object_hash.rb:84:in `[]'
	from /Users/ndbroadbent/.rvm/gems/ruby-2.4.0/gems/pdf-reader-2.0.0/lib/pdf/reader/object_hash.rb:98:in `object'
	from /Users/ndbroadbent/.rvm/gems/ruby-2.4.0/gems/pdf-reader-2.0.0/lib/pdf/reader/object_hash.rb:87:in `[]'
	from /Users/ndbroadbent/.rvm/gems/ruby-2.4.0/gems/pdf-reader-2.0.0/lib/pdf/reader/object_hash.rb:98:in `object'
	from /Users/ndbroadbent/.rvm/gems/ruby-2.4.0/gems/pdf-reader-2.0.0/lib/pdf/reader.rb:136:in `page_count'
	from -e:1:in `<main>'
```

(Downloads the form, then tries to get the page count.)

Is it just a broken PDF? Any way I can workaround cases like this?

This seems to happen with all the forms I'm testing on https://www.uscis.gov

**Comment by ndbroadbent** [comment]
Solved with `qpdf --decrypt`. Added that to the start of all my PDF processing jobs.
