### ISSUE TITLE
ArgumentError: No built-in metrics for Arial

### ISSUE THREAD

**Issue by MathieuDerelle** [yob/pdf-reader#292]
It is impossible to get the text of this [PDF](https://github.com/yob/pdf-reader/files/3197995/5d83bd25-5eb7-41ee-ab8d-5ec87a421567.pdf)

tested versus actual master (2f91e4912c2d)

`pdf.pages.map(&:text)` raises `ArgumentError: No built-in metrics for Arial` 
```
    [ 0] "/Users/mathieu/.rvm/gems/ruby-2.2.9/bundler/gems/pdf-reader-2f91e4912c2d/lib/pdf/reader/width_calculator/built_in.rb:24:in `initialize'",
    [ 1] "/Users/mathieu/.rvm/gems/ruby-2.2.9/bundler/gems/pdf-reader-2f91e4912c2d/lib/pdf/reader/font.rb:93:in `new'",
    [ 2] "/Users/mathieu/.rvm/gems/ruby-2.2.9/bundler/gems/pdf-reader-2f91e4912c2d/lib/pdf/reader/font.rb:93:in `build_width_calculator'",
    [ 3] "/Users/mathieu/.rvm/gems/ruby-2.2.9/bundler/gems/pdf-reader-2f91e4912c2d/lib/pdf/reader/font.rb:47:in `initialize'",
    [ 4] "/Users/mathieu/.rvm/gems/ruby-2.2.9/bundler/gems/pdf-reader-2f91e4912c2d/lib/pdf/reader/page_state.rb:384:in `new'",
    [ 5] "/Users/mathieu/.rvm/gems/ruby-2.2.9/bundler/gems/pdf-reader-2f91e4912c2d/lib/pdf/reader/page_state.rb:384:in `block in build_fonts'",
    [ 6] "/Users/mathieu/.rvm/gems/ruby-2.2.9/bundler/gems/pdf-reader-2f91e4912c2d/lib/pdf/reader/page_state.rb:383:in `each'",
    [ 7] "/Users/mathieu/.rvm/gems/ruby-2.2.9/bundler/gems/pdf-reader-2f91e4912c2d/lib/pdf/reader/page_state.rb:383:in `map'",
    [ 8] "/Users/mathieu/.rvm/gems/ruby-2.2.9/bundler/gems/pdf-reader-2f91e4912c2d/lib/pdf/reader/page_state.rb:383:in `build_fonts'",
    [ 9] "/Users/mathieu/.rvm/gems/ruby-2.2.9/bundler/gems/pdf-reader-2f91e4912c2d/lib/pdf/reader/page_state.rb:29:in `initialize'",
    [10] "/Users/mathieu/.rvm/gems/ruby-2.2.9/bundler/gems/pdf-reader-2f91e4912c2d/lib/pdf/reader/page_text_receiver.rb:43:in `new'",
    [11] "/Users/mathieu/.rvm/gems/ruby-2.2.9/bundler/gems/pdf-reader-2f91e4912c2d/lib/pdf/reader/page_text_receiver.rb:43:in `page='",
    [12] "/Users/mathieu/.rvm/gems/ruby-2.2.9/bundler/gems/pdf-reader-2f91e4912c2d/lib/pdf/reader/page.rb:161:in `block in callback'",
    [13] "/Users/mathieu/.rvm/gems/ruby-2.2.9/bundler/gems/pdf-reader-2f91e4912c2d/lib/pdf/reader/page.rb:160:in `each'",
    [14] "/Users/mathieu/.rvm/gems/ruby-2.2.9/bundler/gems/pdf-reader-2f91e4912c2d/lib/pdf/reader/page.rb:160:in `callback'",
    [15] "/Users/mathieu/.rvm/gems/ruby-2.2.9/bundler/gems/pdf-reader-2f91e4912c2d/lib/pdf/reader/page.rb:111:in `walk'",
    [16] "/Users/mathieu/.rvm/gems/ruby-2.2.9/bundler/gems/pdf-reader-2f91e4912c2d/lib/pdf/reader/page.rb:82:in `text'",
    [17] "(pry):6:in `map'",
    [18] "(pry):6:in `<main>'",
    [19] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `eval'",
    [20] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `evaluate_ruby'",
    [21] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/pry_instance.rb:323:in `handle_line'",
    [22] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'",
    [23] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `catch'",
    [24] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `block in eval'",
    [25] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `catch'",
    [26] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `eval'",
    [27] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/repl.rb:77:in `block in repl'",
    [28] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/repl.rb:67:in `loop'",
    [29] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/repl.rb:67:in `repl'",
    [30] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/repl.rb:38:in `block in start'",
    [31] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/input_lock.rb:61:in `call'",
    [32] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/input_lock.rb:61:in `__with_ownership'",
    [33] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/input_lock.rb:79:in `with_ownership'",
    [34] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/repl.rb:38:in `start'",
    [35] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/repl.rb:15:in `start'",
    [36] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-0.10.4/lib/pry/pry_class.rb:169:in `start'",
    [37] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/pry-byebug-3.4.3/lib/pry-byebug/pry_ext.rb:11:in `start_with_pry_byebug'",
    [38] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/railties-3.2.22.5/lib/rails/commands/console.rb:47:in `start'",
    [39] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/railties-3.2.22.5/lib/rails/commands/console.rb:8:in `start'",
    [40] "/Users/mathieu/.rvm/gems/ruby-2.2.9/gems/railties-3.2.22.5/lib/rails/commands.rb:41:in `<top (required)>'",
    [41] "script/rails:6:in `require'",
    [42] "script/rails:6:in `<main>'"
```

**Comment by mapreal19** [comment]
I've received a similar error but for TimesNewRoman. Any ideas on fixing this?
